// @ts-nocheck
// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-live-signals.ts
import { createClient } from "npm:@supabase/supabase-js@2.49.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_live_signals_default = defineTool({
  name: "list_live_signals",
  title: "List live trading signals",
  description: "Return the current live AI-generated stock/crypto trading signals (BUY/SELL) with confidence, entry price, regime, strategy, and reasoning. Signals expire after 24h.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(25).describe("Max signals to return."),
    signal_type: z.enum(["BUY", "SELL"]).optional().describe("Filter by direction."),
    min_confidence: z.number().min(0).max(100).optional().describe("Minimum confidence score (0-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, signal_type, min_confidence }) => {
    let q = sb().from("live_signals").select("ticker,signal_type,entry_price,confidence,regime,stock_profile,strategy,reasoning,explanation,expires_at,created_at,source").gt("expires_at", (/* @__PURE__ */ new Date()).toISOString()).order("confidence", { ascending: false }).limit(limit);
    if (signal_type) q = q.eq("signal_type", signal_type);
    if (typeof min_confidence === "number") q = q.gte("confidence", min_confidence);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { signals: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-signal.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2.49.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_signal_default = defineTool2({
  name: "get_signal",
  title: "Get live signal for ticker",
  description: "Return the current live trading signal for a specific ticker symbol, if one is active.",
  inputSchema: {
    ticker: z2.string().trim().min(1).max(15).describe("Ticker symbol, e.g. AAPL or BTC-USD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ ticker }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("live_signals").select("*").eq("ticker", ticker.toUpperCase()).gt("expires_at", (/* @__PURE__ */ new Date()).toISOString()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No active signal for ${ticker.toUpperCase()}.` }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { signal: data }
    };
  }
});

// src/lib/mcp/tools/get-stock-price.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_stock_price_default = defineTool3({
  name: "get_stock_price",
  title: "Get current stock price",
  description: "Fetch the latest price and daily change for a stock or crypto ticker via the app's server-side Yahoo Finance proxy.",
  inputSchema: {
    ticker: z3.string().trim().min(1).max(15).describe("Ticker symbol, e.g. AAPL, TSLA, BTC-USD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ ticker }) => {
    const url = `${process.env.SUPABASE_URL}/functions/v1/fetch-stock-price`;
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY}`
      },
      body: JSON.stringify({ ticker: ticker.toUpperCase() })
    });
    const text = await res.text();
    if (!res.ok) return { content: [{ type: "text", text: `Error ${res.status}: ${text}` }], isError: true };
    return { content: [{ type: "text", text }] };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "usestockai-mcp",
  title: "UseStockAI Signals",
  version: "0.1.0",
  instructions: "Tools for UseStockAI. Use `list_live_signals` to browse the current AI-generated BUY/SELL trading signals ranked by confidence, `get_signal` to check the active signal for a specific ticker, and `get_stock_price` to fetch a live quote. Signals are informational, not financial advice.",
  tools: [list_live_signals_default, get_signal_default, get_stock_price_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
